from rich.default_styles import DEFAULT_STYLES
from rich.style import Style

from logre.style.const import *

__all__ = ("HIKARI_STYLES",)


HIKARI_STYLES: dict[str, Style] = DEFAULT_STYLES | {
    # base
    "none": Style.null(),
    "reset": Style(
        color=FOREGROUND,
        bgcolor=BACKGROUND,
        dim=False,
        bold=False,
        italic=False,
        underline=False,
        blink=False,
        blink2=False,
        reverse=False,
        conceal=False,
        strike=False,
    ),
    # base style
    "dim": Style(dim=True),
    "bright": Style(dim=False),
    "bold": Style(bold=True),
    "strong": Style(bold=True),
    "code": Style(reverse=True, bold=True),
    "italic": Style(italic=True),
    "emphasize": Style(italic=True),
    "underline": Style(underline=True),
    "blink": Style(blink=True),
    "blink2": Style(blink2=True),
    "reverse": Style(reverse=True),
    "strike": Style(strike=True),
    # color
    "black": Style(color=BLACK),
    "dark_grey": Style(color=DARK_GREY),
    "light_grey": Style(color=LIGHT_GREY),
    "grey": Style(color=GREY),
    "red": Style(color=RED),
    "bright_red": Style(color=BRIGHT_RED),
    "green": Style(color=GREEN),
    "bright_green": Style(color=BRIGHT_GREEN),
    "yellow": Style(color=YELLOW),
    "bright_yellow": Style(color=BRIGHT_YELLOW),
    "orange": Style(color=ORANGE),
    "purple": Style(color=PURPLE),
    "magenta": Style(color=MAGENTA),
    "bright_magenta": Style(color=BRIGHT_MAGENTA),
    "blue": Style(color=BLUE),
    "bright_blue": Style(color=BRIGHT_BLUE),
    "cyan": Style(color=CYAN),
    "bright_cyan": Style(color=BRIGHT_CYAN),
    "white": Style(color=WHITE),
    "bright_white": Style(color=BRIGHT_WHITE),
    # inspect
    "inspect.async_def": Style(italic=True, color=BRIGHT_CYAN),
    "inspect.attr": Style(color=YELLOW, italic=True),
    "inspect.attr.dunder": Style(color=YELLOW, italic=True, dim=True),
    "inspect.callable": Style(bold=True, color=RED),
    "inspect.def": Style(italic=True, color=BRIGHT_CYAN),
    "inspect.class": Style(italic=True, color=BRIGHT_CYAN),
    "inspect.error": Style(bold=True, color=RED),
    "inspect.equals": Style(),
    "inspect.help": Style(color=CYAN),
    "inspect.doc": Style(dim=True),
    "inspect.value.border": Style(color=GREEN),
    # live
    "live.ellipsis": Style(bold=True, color=RED),
    # layout
    "layout.tree.row": Style(dim=False, color=RED),
    "layout.tree.column": Style(dim=False, color=BLUE),
    # logging
    "logging.prefix": Style(bold=True, color="#FFB84D"),
    "logging.prefix.brackets": Style(bold=True, color="#7C7980"),
    "logging.keyword": Style(bold=True, color=ORANGE),
    "logging.level.notset": Style(color=DARK_GREY, dim=True),
    "logging.level.trace": Style(color=GREY),
    "logging.level.debug": Style(color=LIGHT_GREY, bold=True),
    "logging.level.info": Style(color=WHITE),
    "logging.level.success": Style(color=GREEN),
    "logging.level.warning": Style(color=YELLOW),
    "logging.level.error": Style(color=RED),
    "logging.level.critical": Style(color=RED, bgcolor="#1E0010", bold=True),
    "logging.level": Style.null(),
    "logging.time": Style(color=CYAN, dim=False, bold=True),
    "logging.message": Style.null(),
    "logging.path": Style(dim=True),
    "logging.line_no": Style(color=CYAN, bold=True, italic=False, dim=True),
    # repr
    "repr.ellipsis": Style(color=YELLOW),
    "repr.indent": Style(color=GREEN, dim=True),
    "repr.error": Style(color=RED, bold=True),
    "repr.str": Style(color=GREEN, italic=False, bold=False),
    "repr.brace": Style(bold=True),
    "repr.comma": Style(bold=True),
    "repr.ipv4": Style(bold=True, color=BRIGHT_GREEN),
    "repr.ipv6": Style(bold=True, color=BRIGHT_GREEN),
    "repr.eui48": Style(bold=True, color=BRIGHT_GREEN),
    "repr.eui64": Style(bold=True, color=BRIGHT_GREEN),
    "repr.tag_start": Style(bold=True),
    "repr.tag_name": Style(color=BRIGHT_MAGENTA, bold=True),
    "repr.tag_contents": Style(color="default"),
    "repr.tag_end": Style(bold=True),
    "repr.attrib_name": Style(color=YELLOW, italic=False),
    "repr.attrib_equal": Style(bold=True),
    "repr.attrib_value": Style(color=MAGENTA, italic=False),
    "repr.number": Style(color=CYAN, bold=True, italic=False),
    "repr.number_complex": Style(color=CYAN, bold=True, italic=False),  # same
    "repr.bool_true": Style(color=BRIGHT_GREEN, italic=True),
    "repr.bool_false": Style(color=BRIGHT_RED, italic=True),
    "repr.none": Style(color=MAGENTA, italic=True),
    "repr.url": Style(underline=True, color=BRIGHT_BLUE, italic=False, bold=False),
    "repr.uuid": Style(color=BRIGHT_YELLOW, bold=False),
    "repr.call": Style(color=MAGENTA, bold=True),
    "repr.path": Style(color=MAGENTA),
    "repr.filename": Style(color=BRIGHT_MAGENTA),
    "rule.line": Style(color=BRIGHT_GREEN),
    "rule.text": Style.null(),
    # json
    "json.brace": Style(bold=True),
    "json.bool_true": Style(color=BRIGHT_GREEN, italic=True),
    "json.bool_false": Style(color=BRIGHT_RED, italic=True),
    "json.null": Style(color=MAGENTA, italic=True),
    "json.number": Style(color=CYAN, bold=True, italic=False),
    "json.str": Style(color=GREEN, italic=False, bold=False),
    "json.key": Style(color=BLUE, bold=True),
    # prompt
    "prompt": Style.null(),
    "prompt.choices": Style(color=MAGENTA, bold=True),
    "prompt.default": Style(color=CYAN, bold=True),
    "prompt.invalid": Style(color=RED),
    "prompt.invalid.choice": Style(color=RED),
    # pretty
    "pretty": Style.null(),
    # scope
    "scope.border": Style(color=BLUE),
    "scope.key": Style(color=YELLOW, italic=True),
    "scope.key.special": Style(color=YELLOW, italic=True, dim=True),
    "scope.equals": Style(color=RED),
    # table
    "table.header": Style(bold=True),
    "table.footer": Style(bold=True),
    "table.cell": Style.null(),
    "table.title": Style(italic=True),
    "table.caption": Style(italic=True, dim=True),
    # traceback
    "traceback.error": Style(color=RED, italic=True),
    "traceback.border.syntax_error": Style(color=BRIGHT_RED),
    "traceback.border": Style(color=RED),
    "traceback.text": Style.null(),
    "traceback.title": Style(color=RED, bold=True),
    "traceback.exc_type": Style(color=BRIGHT_RED, bold=True),
    "traceback.exc_value": Style.null(),
    "traceback.offset": Style(color=BRIGHT_RED, bold=True),
    # bar
    "bar.back": Style(color="grey23"),
    "bar.complete": Style(color="rgb(249,38,114)"),
    "bar.finished": Style(color="rgb(114,156,31)"),
    "bar.pulse": Style(color="rgb(249,143,36)"),
    # progress
    "progress.description": Style.null(),
    "progress.filesize": Style(color=GREEN),
    "progress.filesize.total": Style(color=GREEN),
    "progress.download": Style(color=GREEN),
    "progress.elapsed": Style(color=YELLOW),
    "progress.percentage": Style(color=MAGENTA),
    "progress.remaining": Style(color=CYAN),
    "progress.data.speed": Style(color=RED),
    "progress.spinner": Style(color=GREEN),
    "status.spinner": Style(color=GREEN),
    # tree
    "tree": Style(),
    "tree.line": Style(),
    # markdown
    "markdown.paragraph": Style(),
    "markdown.text": Style(),
    "markdown.em": Style(italic=True),
    "markdown.emph": Style(italic=True),
    "markdown.strong": Style(bold=True),
    "markdown.code": Style(bgcolor=BLACK, color=BRIGHT_WHITE),
    "markdown.code_block": Style(dim=True, color=CYAN, bgcolor=BLACK),
    "markdown.block_quote": Style(color=MAGENTA),
    "markdown.list": Style(color=CYAN),
    "markdown.item": Style(),
    "markdown.item.bullet": Style(color=YELLOW, bold=True),
    "markdown.item.number": Style(color=YELLOW, bold=True),
    "markdown.hr": Style(color=YELLOW),
    "markdown.h1.border": Style(),
    "markdown.h1": Style(bold=True),
    "markdown.h2": Style(bold=True, underline=True),
    "markdown.h3": Style(bold=True),
    "markdown.h4": Style(bold=True, dim=True),
    "markdown.h5": Style(underline=True),
    "markdown.h6": Style(italic=True),
    "markdown.h7": Style(italic=True, dim=True),
    "markdown.link": Style(color=BRIGHT_BLUE),
    "markdown.link_url": Style(color=BLUE),
    "markdown.s": Style(strike=True),
    # iso8601
    "iso8601.date": Style(color=BLUE),
    "iso8601.time": Style(color=MAGENTA),
    "iso8601.timezone": Style(color=YELLOW),
}
